name: Anchore syft SBOM commit

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  retrieve-sboms:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: test variable stuff
      run: |
        echo "HOME=$HOME"
        echo "{{ env.HOME }}=${{ env.HOME }}"
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
        echo "{{ env.GITHUB_WORKSPACE }}=${{ env.GITHUB_WORKSPACE }}"
        set -x
        export BASE_DIR=$(pwd)
        echo BASE_DIR=$BASE_DIR >> $GITHUB_ENV
        echo "BASE_DIR=$BASE_DIR"
        echo "{{ env.BASE_DIR }}=${{ env.BASE_DIR }}"
        false  # fail
    #     env | sort
    #     env | sort | grep test-sbom
    #     pwd

    - name: checkout target repo
      run: |
        mkdir wip
        cd wip
        git clone \
          --depth 1 \
          --single-branch \
          https://github.com/mozilla/kitsune.git target

    - name: generate sboms
      uses: anchore/sbom-action@v0
      with:
        path: ./wip/target/
          # artifact name wants an abs path
        artifact-name: ${{ env.GITHUB_WORKSPACE }}/wip/mozilla-kitsune.json
        # repo_list_path: repo-list.txt
        # save_directory_path: wip
        # github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: move the anchore files to their final spot
      run: |
        mkdir -p anchore-syft/mozilla
        mv ./wip/mozilla-kitsune.json anchore-syft/mozilla/kitsune.json

    # - name: commit any changes
    #   run: |
    #     git config user.name "hwine"
    #     git config user.email "132412+hwine@users.noreply.github.com"
    #     git add .
    #     # we may not have added anything, so allow the commit to fail
    #     # TODO: find a better test to _only_ allow no-change-error to be suppressed
    #     git commit --message "update from workflow" || true
    #     git push
