name: SBOM commit trial

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  retrieve-sboms:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: try it
      uses: Brend-Smits/github-sbom-generator-action@v1.1.0
      with:
        repo_list_path: repo-list.txt
        save_directory_path: .
        github_token: ${{ secrets.GITHUB_TOKEN }}
##    - name: upload
##      uses: actions/upload-artifact@v3
##      with:
##        name: all-repos-sboms
##        path: sboms

    - name: commit any changes
      run: |
        git config user.name "hwine"
        git config user.email "132412+hwine@users.noreply.github.com"
        git add .
        git commit --message "update from workflow"
